#!/system/bin/sh
READ_AHEAD_KB=3072

#Cpu Boost
echo "0" > /sys/module/cpu_boost/parameters/cpu_boost

# Tweak kernel scheduler
echo "384" > /proc/sys/kernel/random/write_wakeup_threshold
echo "384" > /proc/sys/kernel/random/read_wakeup_threshold
echo "500000" > /proc/sys/kernel/sched_min_granularity_ns
echo "1000000" > /proc/sys/kernel/sched_latency_ns
echo "100000" > /proc/sys/kernel/sched_wakeup_granularity_ns

# suitable configuration to help reduce network latency
echo 2 > /proc/sys/net/ipv4/tcp_ecn
echo 1 > /proc/sys/net/ipv4/tcp_sack
echo 1 > /proc/sys/net/ipv4/tcp_dsack
echo 1 > /proc/sys/net/ipv4/tcp_low_latency
echo 1 > /proc/sys/net/ipv4/tcp_timestamps

echo 1 > /proc/sys/net/ipv4/route/flush
echo 1 > /proc/sys/net/ipv4/tcp_rfc1337
echo 0 > /proc/sys/net/ipv4/ip_no_pmtu_disc
echo 1 > /proc/sys/net/ipv4/tcp_fack
echo 1 > /proc/sys/net/ipv4/tcp_window_scaling
echo "4096 39000 187000" > /proc/sys/net/ipv4/tcp_rmem
echo "4096 39000 187000" > /proc/sys/net/ipv4/tcp_wmem
echo "187000 187000 187000" > /proc/sys/net/ipv4/tcp_mem
echo 1 > /proc/sys/net/ipv4/tcp_no_metrics_save
echo 1 > /proc/sys/net/ipv4/tcp_moderate_rcvbuf

#Ramdisk Tweaks
echo "$READ_AHEAD_KB" > /sys/devices/virtual/bdi/179:0/read_ahead_kb
echo "4096" > /proc/sys/vm/min_free_kbytes;
echo "1" > /proc/sys/vm/vfs_cache_pressure;
echo "90" > /proc/sys/vm/dirty_ratio;
echo "5" > /proc/sys/vm/dirty_background_ratio;
echo "1000" > /proc/sys/vm/dirty_writeback_centisecs;
echo "200" > /proc/sys/vm/dirty_expire_centisecs;

